language: node_js
node_js: "8.11.2"

addons:
  apt:
    packages:
      - xvfb
      - libusb-1.0-0-dev

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - npm install

  # TODO build?

script:
  # export DISPLAY=:99.0
  # sh -e /etc/init.d/xvfb start
  # sleep 3
  - npm run eslint
  - npm test

cache:
  directories:
    - node_modules
