version: 2
jobs:
  test-node-10:
    working_directory: ~/new-desktop-wallet
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install required packages
          command: |
            sudo apt-get update
            sudo apt-get install libudev-dev libusb-1.0-0-dev
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: yarn global add node-gyp && yarn install && npm rebuild
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Unit tests
          command: yarn test:unit --ci --coverage --maxWorkers 4
      - run:
          name: e2e tests
          command: yarn test:e2e:full --coverage
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Depcheck
          command: yarn depcheck
      - run:
          name: Codecov
          command: ./node_modules/.bin/codecov

workflows:
  version: 2
  test:
    jobs:
      - test-node-10
