name: Compress

on:
    pull_request:
        paths:
            - "**.svg"

jobs:
    svg:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: ericcornelissen/svgo-action@v1.0.1
              with:
                  comment: true
                  conventional-commits: true
                  repo-token: ${{ secrets.GH_TOKEN }}
